test: add cypress testing suite to chronograf
influxdata/chronograf pull request #5809
Opened 2021-09-20 12:59 UTC by Iszy-Ami

This PR adds new e2e cypress tests and configures Circle CI to execute them automatically on every git change.
Testing of components in Chronograf, especially for creating dashboard (variables), setting graf in explorer, manual adding data through write data button and snapshot testing of single stats in grafs.

  
  
  - [ ] Rebased/mergeable
  - [ ] Tests pass

2021-09-29 08:26 UTC, rhajek requested changes
Please remove unnecessary influxdb-onboarding.sh script.

2021-09-29 08:26 UTC, rhajek commented on etc/scripts/influxdb-onboarding.sh
> +#!/usr/bin/env bash
An onboarding script is not necessary now, it it possible to initialise database using environment properties like this:

```
docker run -d -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e DOCKER_INFLUXDB_INIT_MODE=setup \
      -e DOCKER_INFLUXDB_INIT_USERNAME=my-user \
      -e DOCKER_INFLUXDB_INIT_PASSWORD=my-password \
      -e DOCKER_INFLUXDB_INIT_ORG=my-org \
      -e DOCKER_INFLUXDB_INIT_BUCKET=my-bucket \
      -e DOCKER_INFLUXDB_INIT_RETENTION=1w \
      -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token \
      influxdb:2.0
```

2021-09-29 08:26 UTC, rhajek commented on .circleci/config.yml
> +          name: "Post onBoarding request to InfluxDB 2"
onboarding script s not necessary, you can use env properties to setup docker instance:
```
docker run -d -p 8086:8086 \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e DOCKER_INFLUXDB_INIT_MODE=setup \
      -e DOCKER_INFLUXDB_INIT_USERNAME=my-user \
      -e DOCKER_INFLUXDB_INIT_PASSWORD=my-password \
      -e DOCKER_INFLUXDB_INIT_ORG=my-org \
      -e DOCKER_INFLUXDB_INIT_BUCKET=my-bucket \
      -e DOCKER_INFLUXDB_INIT_RETENTION=1w \
      -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token \
      influxdb:2.0
```

2022-02-28 15:21 UTC, sranka commented
Closing, feel free to create a new PR after applying a new strategy for testing (InfluxDB enterprise first).

2022-02-28 15:21 UTC, closed without merging